db:
  image: mysql:5.6
  expose:
    - "3306"
  environment:
    MYSQL_DATABASE: todobackend
    MYSQL_USER: todo
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password

app:
  build: ../../
  dockerfile: docker/release/Dockerfile
  links:
    - db
  environment:
    DJANGO_SETTINGS_MODULE: todobackend.settings.release
    MYSQL_HOST: db
    MYSQL_USER: todo
    MYSQL_PASSWORD: password
#    DEBUG: "True"
  volumes_from:
    - webroot
  command:
    - uwsgi
    - "--socket /var/www/todobackend/todobackend.sock"
    - "--chmod-socket=666"
    - "--module todobackend.wsgi"
    - "--master"
    - "--die-on-term"

webroot:
  build: ../../
  dockerfile: docker/release/Dockerfile
  volumes:
    - /var/www/todobackend
  entrypoint: "true"

nginx:
  build: .
  dockerfile: Dockerfile.nginx
  links:
    - app
  ports:
    - "8000:8000"
  volumes_from:
    - webroot

test:
  image: todobackend-specs
  links:
    - nginx
  environment:
    URL: http://nginx:8000/todos
    JUNIT_REPORT_PATH: /reports/acceptance.xml
    JUNIT_REPORT_STACK: 1
  # command: --reporter mocha-jenkins-reporter

agent:
  image: todo-ansible:latest
  volumes:
    - ../../ansible/:/ansible/
  links:
    - db
  environment:
    PROBE_HOST: "db"
    PROBE_PORT: "3306"